ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_RESPONSE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_FLAGGED';
ALTER TYPE "AuditAction" ADD VALUE 'REVIEW_LIST_VIEWED';
ALTER TABLE "doctors" ADD COLUMN "isProfileVisible" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN "ratingReviewRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "patients" ADD COLUMN "appointmentDiscountBps" INTEGER NOT NULL DEFAULT 0;
CREATE TABLE "reviews" ("id" TEXT NOT NULL, "appointmentId" TEXT NOT NULL, "patientId" TEXT NOT NULL, "doctorId" TEXT NOT NULL, "rating" INTEGER NOT NULL, "comment" VARCHAR(1000), "displayAnonymous" BOOLEAN NOT NULL DEFAULT true, "isVerified" BOOLEAN NOT NULL DEFAULT true, "flaggedAt" TIMESTAMP(3), "flagReason" VARCHAR(500), "isDeleted" BOOLEAN NOT NULL DEFAULT false, "deletedAt" TIMESTAMP(3), "deletedByUserId" VARCHAR(100), "deletionReason" VARCHAR(500), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "reviews_pkey" PRIMARY KEY ("id"));
CREATE TABLE "review_responses" ("id" TEXT NOT NULL, "reviewId" TEXT NOT NULL, "doctorId" TEXT NOT NULL, "response" VARCHAR(500) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "review_responses_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "reviews_appointmentId_key" ON "reviews"("appointmentId");
CREATE INDEX "idx_review_doctor_public" ON "reviews"("doctorId", "isDeleted", "createdAt" DESC);
CREATE INDEX "idx_review_patient_created" ON "reviews"("patientId", "createdAt" DESC);
CREATE INDEX "idx_review_rating" ON "reviews"("rating", "isDeleted");
CREATE INDEX "idx_review_flaggedAt" ON "reviews"("flaggedAt");
CREATE UNIQUE INDEX "review_responses_reviewId_key" ON "review_responses"("reviewId");
CREATE INDEX "idx_review_response_doctor_created" ON "review_responses"("doctorId", "createdAt" DESC);
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "review_responses" ADD CONSTRAINT "review_responses_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "reviews"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_rating_check" CHECK ("rating" BETWEEN 1 AND 5);
ALTER TABLE "patients" ADD CONSTRAINT "patients_appointmentDiscountBps_check" CHECK ("appointmentDiscountBps" BETWEEN 0 AND 10000);
