ALTER TYPE "AuditAction" ADD VALUE 'PRESCRIPTION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'PRESCRIPTION_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'PRESCRIPTION_VIEWED';
ALTER TYPE "AuditAction" ADD VALUE 'PRESCRIPTION_PDF_GENERATED';
ALTER TYPE "AuditAction" ADD VALUE 'PRESCRIPTION_DOWNLOADED';
ALTER TYPE "AuditAction" ADD VALUE 'PRESCRIPTION_REMINDER_SENT';

CREATE TABLE "prescriptions" ("id" TEXT NOT NULL, "prescriptionNumber" VARCHAR(100) NOT NULL, "appointmentId" TEXT NOT NULL, "doctorId" TEXT NOT NULL, "patientId" TEXT NOT NULL, "instructions" VARCHAR(5000) NOT NULL, "followUpDate" DATE, "version" INTEGER NOT NULL DEFAULT 1, "reminderSentAt" TIMESTAMP(3), "retentionUntil" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "prescriptions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "prescription_medicines" ("id" TEXT NOT NULL, "prescriptionId" TEXT NOT NULL, "name" VARCHAR(200) NOT NULL, "dosage" VARCHAR(100) NOT NULL, "frequency" VARCHAR(100) NOT NULL, "duration" VARCHAR(100) NOT NULL, "instructions" VARCHAR(500), "sortOrder" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "prescription_medicines_pkey" PRIMARY KEY ("id"));
CREATE TABLE "prescription_versions" ("id" TEXT NOT NULL, "prescriptionId" TEXT NOT NULL, "version" INTEGER NOT NULL, "instructions" VARCHAR(5000) NOT NULL, "followUpDate" DATE, "medicines" JSONB NOT NULL, "changedByUserId" VARCHAR(100) NOT NULL, "overrideReason" VARCHAR(500), "objectKey" VARCHAR(1024), "fileUrl" VARCHAR(2048), "checksum" CHAR(64), "sizeBytes" INTEGER, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "prescription_versions_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "prescriptions_prescriptionNumber_key" ON "prescriptions"("prescriptionNumber");
CREATE UNIQUE INDEX "prescriptions_appointmentId_key" ON "prescriptions"("appointmentId");
CREATE INDEX "idx_prescription_patient_created" ON "prescriptions"("patientId", "createdAt" DESC);
CREATE INDEX "idx_prescription_doctor_created" ON "prescriptions"("doctorId", "createdAt" DESC);
CREATE INDEX "idx_prescription_followUpDate" ON "prescriptions"("followUpDate");
CREATE INDEX "idx_prescription_medicine_order" ON "prescription_medicines"("prescriptionId", "sortOrder");
CREATE UNIQUE INDEX "prescription_versions_objectKey_key" ON "prescription_versions"("objectKey");
CREATE UNIQUE INDEX "prescription_version_key" ON "prescription_versions"("prescriptionId", "version");
CREATE INDEX "idx_prescription_version_created" ON "prescription_versions"("prescriptionId", "createdAt" DESC);
ALTER TABLE "prescriptions" ADD CONSTRAINT "prescriptions_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "prescriptions" ADD CONSTRAINT "prescriptions_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "prescriptions" ADD CONSTRAINT "prescriptions_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "prescription_medicines" ADD CONSTRAINT "prescription_medicines_prescriptionId_fkey" FOREIGN KEY ("prescriptionId") REFERENCES "prescriptions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "prescription_versions" ADD CONSTRAINT "prescription_versions_prescriptionId_fkey" FOREIGN KEY ("prescriptionId") REFERENCES "prescriptions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
